/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
export interface Activity {
    id: number;
    cityId: number;
    name: string;
    cityName: string;
    category: string;
    description: string;
    image: string;
    durationMinutes: number;
    estimatedCost: number;
    rating: number;
}
//# sourceMappingURL=activity.d.ts.map