/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary Get dashboard overview
 */
export declare const GetDashboardResponse: zod.ZodObject<{
    profile: zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        email: zod.ZodString;
        country: zod.ZodString;
        initials: zod.ZodOptional<zod.ZodString>;
    }, zod.z.core.$strip>;
    stats: zod.ZodObject<{
        totalTrips: zod.ZodInt;
        daysPlanned: zod.ZodInt;
        estimatedBudget: zod.ZodNumber;
        citiesVisited: zod.ZodInt;
    }, zod.z.core.$strip>;
    upcomingTrips: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        description: zod.ZodString;
        startDate: zod.z.ZodCoercedDate<unknown>;
        endDate: zod.z.ZodCoercedDate<unknown>;
        budget: zod.ZodNumber;
        currency: zod.ZodString;
        status: zod.ZodString;
        cities: zod.ZodInt;
        activities: zod.ZodInt;
        coverImage: zod.ZodString;
        isPublic: zod.ZodBoolean;
    }, zod.z.core.$strip>>;
    destinations: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        country: zod.ZodString;
        region: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        costIndex: zod.ZodString;
        popularity: zod.ZodNumber;
    }, zod.z.core.$strip>>;
}, zod.z.core.$strip>;
/**
 * @summary List trips
 */
export declare const ListTripsQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.z.ZodCoercedString<unknown>>;
}, zod.z.core.$strip>;
export declare const ListTripsResponseItem: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>;
export declare const ListTripsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>>;
/**
 * @summary Create a trip
 */
export declare const createTripBodyBudgetMin = 0;
export declare const CreateTripBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodOptional<zod.ZodNumber>;
    currency: zod.ZodOptional<zod.ZodString>;
    coverImage: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const CreateTripResponse: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>;
/**
 * @summary Get a trip
 */
export declare const GetTripParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const GetTripResponse: zod.ZodIntersection<zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>, zod.ZodObject<{
    stops: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        tripId: zod.ZodInt;
        city: zod.ZodObject<{
            id: zod.ZodInt;
            name: zod.ZodString;
            country: zod.ZodString;
            region: zod.ZodString;
            description: zod.ZodString;
            image: zod.ZodString;
            costIndex: zod.ZodString;
            popularity: zod.ZodNumber;
        }, zod.z.core.$strip>;
        arrivalDate: zod.z.ZodCoercedDate<unknown>;
        departureDate: zod.z.ZodCoercedDate<unknown>;
        stopOrder: zod.ZodInt;
        notes: zod.ZodString;
    }, zod.z.core.$strip>>;
    tripActivities: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        tripId: zod.ZodInt;
        stopId: zod.ZodInt;
        activity: zod.ZodObject<{
            id: zod.ZodInt;
            cityId: zod.ZodInt;
            name: zod.ZodString;
            cityName: zod.ZodString;
            category: zod.ZodString;
            description: zod.ZodString;
            image: zod.ZodString;
            durationMinutes: zod.ZodInt;
            estimatedCost: zod.ZodNumber;
            rating: zod.ZodNumber;
        }, zod.z.core.$strip>;
        activityDate: zod.z.ZodCoercedDate<unknown>;
        startTime: zod.ZodString;
        durationMinutes: zod.ZodInt;
        cost: zod.ZodNumber;
        notes: zod.ZodString;
    }, zod.z.core.$strip>>;
}, zod.z.core.$strip>>;
/**
 * @summary Update a trip
 */
export declare const UpdateTripParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const updateTripBodyBudgetMin = 0;
export declare const UpdateTripBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    budget: zod.ZodOptional<zod.ZodNumber>;
    isPublic: zod.ZodOptional<zod.ZodBoolean>;
}, zod.z.core.$strip>;
export declare const UpdateTripResponse: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>;
/**
 * @summary Delete a trip
 */
export declare const DeleteTripParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const DeleteTripResponse: zod.ZodVoid;
/**
 * @summary List trip stops
 */
export declare const ListStopsParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const ListStopsResponseItem: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    city: zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        country: zod.ZodString;
        region: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        costIndex: zod.ZodString;
        popularity: zod.ZodNumber;
    }, zod.z.core.$strip>;
    arrivalDate: zod.z.ZodCoercedDate<unknown>;
    departureDate: zod.z.ZodCoercedDate<unknown>;
    stopOrder: zod.ZodInt;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
export declare const ListStopsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    city: zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        country: zod.ZodString;
        region: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        costIndex: zod.ZodString;
        popularity: zod.ZodNumber;
    }, zod.z.core.$strip>;
    arrivalDate: zod.z.ZodCoercedDate<unknown>;
    departureDate: zod.z.ZodCoercedDate<unknown>;
    stopOrder: zod.ZodInt;
    notes: zod.ZodString;
}, zod.z.core.$strip>>;
/**
 * @summary Add a city stop
 */
export declare const CreateStopParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const CreateStopBody: zod.ZodObject<{
    cityId: zod.ZodInt;
    arrivalDate: zod.z.ZodCoercedDate<unknown>;
    departureDate: zod.z.ZodCoercedDate<unknown>;
    notes: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const CreateStopResponse: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    city: zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        country: zod.ZodString;
        region: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        costIndex: zod.ZodString;
        popularity: zod.ZodNumber;
    }, zod.z.core.$strip>;
    arrivalDate: zod.z.ZodCoercedDate<unknown>;
    departureDate: zod.z.ZodCoercedDate<unknown>;
    stopOrder: zod.ZodInt;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary Update a stop
 */
export declare const UpdateStopParams: zod.ZodObject<{
    stopId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const UpdateStopBody: zod.ZodObject<{
    arrivalDate: zod.ZodOptional<zod.z.ZodCoercedDate<unknown>>;
    departureDate: zod.ZodOptional<zod.z.ZodCoercedDate<unknown>>;
    notes: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const UpdateStopResponse: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    city: zod.ZodObject<{
        id: zod.ZodInt;
        name: zod.ZodString;
        country: zod.ZodString;
        region: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        costIndex: zod.ZodString;
        popularity: zod.ZodNumber;
    }, zod.z.core.$strip>;
    arrivalDate: zod.z.ZodCoercedDate<unknown>;
    departureDate: zod.z.ZodCoercedDate<unknown>;
    stopOrder: zod.ZodInt;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary Delete a stop
 */
export declare const DeleteStopParams: zod.ZodObject<{
    stopId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const DeleteStopResponse: zod.ZodVoid;
/**
 * @summary List trip activities
 */
export declare const ListTripActivitiesParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const ListTripActivitiesResponseItem: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    stopId: zod.ZodInt;
    activity: zod.ZodObject<{
        id: zod.ZodInt;
        cityId: zod.ZodInt;
        name: zod.ZodString;
        cityName: zod.ZodString;
        category: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        durationMinutes: zod.ZodInt;
        estimatedCost: zod.ZodNumber;
        rating: zod.ZodNumber;
    }, zod.z.core.$strip>;
    activityDate: zod.z.ZodCoercedDate<unknown>;
    startTime: zod.ZodString;
    durationMinutes: zod.ZodInt;
    cost: zod.ZodNumber;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
export declare const ListTripActivitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    stopId: zod.ZodInt;
    activity: zod.ZodObject<{
        id: zod.ZodInt;
        cityId: zod.ZodInt;
        name: zod.ZodString;
        cityName: zod.ZodString;
        category: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        durationMinutes: zod.ZodInt;
        estimatedCost: zod.ZodNumber;
        rating: zod.ZodNumber;
    }, zod.z.core.$strip>;
    activityDate: zod.z.ZodCoercedDate<unknown>;
    startTime: zod.ZodString;
    durationMinutes: zod.ZodInt;
    cost: zod.ZodNumber;
    notes: zod.ZodString;
}, zod.z.core.$strip>>;
/**
 * @summary Add an activity to a trip
 */
export declare const AddTripActivityParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const addTripActivityBodyCostMin = 0;
export declare const AddTripActivityBody: zod.ZodObject<{
    stopId: zod.ZodInt;
    activityId: zod.ZodInt;
    activityDate: zod.z.ZodCoercedDate<unknown>;
    startTime: zod.ZodString;
    cost: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const AddTripActivityResponse: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    stopId: zod.ZodInt;
    activity: zod.ZodObject<{
        id: zod.ZodInt;
        cityId: zod.ZodInt;
        name: zod.ZodString;
        cityName: zod.ZodString;
        category: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        durationMinutes: zod.ZodInt;
        estimatedCost: zod.ZodNumber;
        rating: zod.ZodNumber;
    }, zod.z.core.$strip>;
    activityDate: zod.z.ZodCoercedDate<unknown>;
    startTime: zod.ZodString;
    durationMinutes: zod.ZodInt;
    cost: zod.ZodNumber;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary Update a trip activity
 */
export declare const UpdateTripActivityParams: zod.ZodObject<{
    activityId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const updateTripActivityBodyCostMin = 0;
export declare const UpdateTripActivityBody: zod.ZodObject<{
    activityDate: zod.ZodOptional<zod.z.ZodCoercedDate<unknown>>;
    startTime: zod.ZodOptional<zod.ZodString>;
    cost: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const UpdateTripActivityResponse: zod.ZodObject<{
    id: zod.ZodInt;
    tripId: zod.ZodInt;
    stopId: zod.ZodInt;
    activity: zod.ZodObject<{
        id: zod.ZodInt;
        cityId: zod.ZodInt;
        name: zod.ZodString;
        cityName: zod.ZodString;
        category: zod.ZodString;
        description: zod.ZodString;
        image: zod.ZodString;
        durationMinutes: zod.ZodInt;
        estimatedCost: zod.ZodNumber;
        rating: zod.ZodNumber;
    }, zod.z.core.$strip>;
    activityDate: zod.z.ZodCoercedDate<unknown>;
    startTime: zod.ZodString;
    durationMinutes: zod.ZodInt;
    cost: zod.ZodNumber;
    notes: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary Remove an activity
 */
export declare const DeleteTripActivityParams: zod.ZodObject<{
    activityId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const DeleteTripActivityResponse: zod.ZodVoid;
/**
 * @summary Calculate trip budget
 */
export declare const GetTripBudgetParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const GetTripBudgetResponse: zod.ZodObject<{
    total: zod.ZodNumber;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    averagePerDay: zod.ZodNumber;
    durationDays: zod.ZodInt;
    categories: zod.ZodArray<zod.ZodObject<{
        name: zod.ZodString;
        value: zod.ZodNumber;
        color: zod.ZodString;
    }, zod.z.core.$strip>>;
}, zod.z.core.$strip>;
/**
 * @summary Search cities
 */
export declare const ListCitiesQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.z.ZodCoercedString<unknown>>;
    region: zod.ZodOptional<zod.z.ZodCoercedString<unknown>>;
}, zod.z.core.$strip>;
export declare const ListCitiesResponseItem: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    country: zod.ZodString;
    region: zod.ZodString;
    description: zod.ZodString;
    image: zod.ZodString;
    costIndex: zod.ZodString;
    popularity: zod.ZodNumber;
}, zod.z.core.$strip>;
export declare const ListCitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    country: zod.ZodString;
    region: zod.ZodString;
    description: zod.ZodString;
    image: zod.ZodString;
    costIndex: zod.ZodString;
    popularity: zod.ZodNumber;
}, zod.z.core.$strip>>;
/**
 * @summary Search activities
 */
export declare const ListActivitiesQueryParams: zod.ZodObject<{
    search: zod.ZodOptional<zod.z.ZodCoercedString<unknown>>;
    category: zod.ZodOptional<zod.z.ZodCoercedString<unknown>>;
}, zod.z.core.$strip>;
export declare const ListActivitiesResponseItem: zod.ZodObject<{
    id: zod.ZodInt;
    cityId: zod.ZodInt;
    name: zod.ZodString;
    cityName: zod.ZodString;
    category: zod.ZodString;
    description: zod.ZodString;
    image: zod.ZodString;
    durationMinutes: zod.ZodInt;
    estimatedCost: zod.ZodNumber;
    rating: zod.ZodNumber;
}, zod.z.core.$strip>;
export declare const ListActivitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodInt;
    cityId: zod.ZodInt;
    name: zod.ZodString;
    cityName: zod.ZodString;
    category: zod.ZodString;
    description: zod.ZodString;
    image: zod.ZodString;
    durationMinutes: zod.ZodInt;
    estimatedCost: zod.ZodNumber;
    rating: zod.ZodNumber;
}, zod.z.core.$strip>>;
/**
 * @summary Create a public share link
 */
export declare const ShareTripParams: zod.ZodObject<{
    tripId: zod.z.ZodCoercedNumber<unknown>;
}, zod.z.core.$strip>;
export declare const ShareTripResponse: zod.ZodObject<{
    token: zod.ZodString;
    url: zod.ZodString;
}, zod.z.core.$strip>;
/**
 * @summary View a shared trip
 */
export declare const GetSharedTripParams: zod.ZodObject<{
    token: zod.z.ZodCoercedString<unknown>;
}, zod.z.core.$strip>;
export declare const GetSharedTripResponse: zod.ZodIntersection<zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    description: zod.ZodString;
    startDate: zod.z.ZodCoercedDate<unknown>;
    endDate: zod.z.ZodCoercedDate<unknown>;
    budget: zod.ZodNumber;
    currency: zod.ZodString;
    status: zod.ZodString;
    cities: zod.ZodInt;
    activities: zod.ZodInt;
    coverImage: zod.ZodString;
    isPublic: zod.ZodBoolean;
}, zod.z.core.$strip>, zod.ZodObject<{
    stops: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        tripId: zod.ZodInt;
        city: zod.ZodObject<{
            id: zod.ZodInt;
            name: zod.ZodString;
            country: zod.ZodString;
            region: zod.ZodString;
            description: zod.ZodString;
            image: zod.ZodString;
            costIndex: zod.ZodString;
            popularity: zod.ZodNumber;
        }, zod.z.core.$strip>;
        arrivalDate: zod.z.ZodCoercedDate<unknown>;
        departureDate: zod.z.ZodCoercedDate<unknown>;
        stopOrder: zod.ZodInt;
        notes: zod.ZodString;
    }, zod.z.core.$strip>>;
    tripActivities: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodInt;
        tripId: zod.ZodInt;
        stopId: zod.ZodInt;
        activity: zod.ZodObject<{
            id: zod.ZodInt;
            cityId: zod.ZodInt;
            name: zod.ZodString;
            cityName: zod.ZodString;
            category: zod.ZodString;
            description: zod.ZodString;
            image: zod.ZodString;
            durationMinutes: zod.ZodInt;
            estimatedCost: zod.ZodNumber;
            rating: zod.ZodNumber;
        }, zod.z.core.$strip>;
        activityDate: zod.z.ZodCoercedDate<unknown>;
        startTime: zod.ZodString;
        durationMinutes: zod.ZodInt;
        cost: zod.ZodNumber;
        notes: zod.ZodString;
    }, zod.z.core.$strip>>;
}, zod.z.core.$strip>>;
/**
 * @summary Get current profile
 */
export declare const GetProfileResponse: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    email: zod.ZodString;
    country: zod.ZodString;
    initials: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
/**
 * @summary Update current profile
 */
export declare const UpdateProfileBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    country: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
export declare const UpdateProfileResponse: zod.ZodObject<{
    id: zod.ZodInt;
    name: zod.ZodString;
    email: zod.ZodString;
    country: zod.ZodString;
    initials: zod.ZodOptional<zod.ZodString>;
}, zod.z.core.$strip>;
//# sourceMappingURL=api.d.ts.map