/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get dashboard overview
 */
export const GetDashboardResponse = zod.object({
  "profile": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "email": zod.string(),
  "country": zod.string(),
  "initials": zod.string().optional()
}),
  "stats": zod.object({
  "totalTrips": zod.int(),
  "daysPlanned": zod.int(),
  "estimatedBudget": zod.number(),
  "citiesVisited": zod.int()
}),
  "upcomingTrips": zod.array(zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
})),
  "destinations": zod.array(zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}))
})


/**
 * @summary List trips
 */
export const ListTripsQueryParams = zod.object({
  "status": zod.coerce.string().optional()
})

export const ListTripsResponseItem = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
})
export const ListTripsResponse = zod.array(ListTripsResponseItem)


/**
 * @summary Create a trip
 */

export const createTripBodyBudgetMin = 0;



export const CreateTripBody = zod.object({
  "name": zod.string().min(1),
  "description": zod.string().optional(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number().min(createTripBodyBudgetMin).optional(),
  "currency": zod.string().optional(),
  "coverImage": zod.string().optional()
})

export const CreateTripResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
})


/**
 * @summary Get a trip
 */
export const GetTripParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const GetTripResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
}).and(zod.object({
  "stops": zod.array(zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "city": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "stopOrder": zod.int(),
  "notes": zod.string()
})),
  "tripActivities": zod.array(zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "stopId": zod.int(),
  "activity": zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
}),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "durationMinutes": zod.int(),
  "cost": zod.number(),
  "notes": zod.string()
}))
}))


/**
 * @summary Update a trip
 */
export const UpdateTripParams = zod.object({
  "tripId": zod.coerce.number().int()
})


export const updateTripBodyBudgetMin = 0;



export const UpdateTripBody = zod.object({
  "name": zod.string().min(1).optional(),
  "description": zod.string().optional(),
  "budget": zod.number().min(updateTripBodyBudgetMin).optional(),
  "isPublic": zod.boolean().optional()
})

export const UpdateTripResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
})


/**
 * @summary Delete a trip
 */
export const DeleteTripParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const DeleteTripResponse = zod.void()


/**
 * @summary List trip stops
 */
export const ListStopsParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const ListStopsResponseItem = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "city": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "stopOrder": zod.int(),
  "notes": zod.string()
})
export const ListStopsResponse = zod.array(ListStopsResponseItem)


/**
 * @summary Add a city stop
 */
export const CreateStopParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const CreateStopBody = zod.object({
  "cityId": zod.int(),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "notes": zod.string().optional()
})

export const CreateStopResponse = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "city": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "stopOrder": zod.int(),
  "notes": zod.string()
})


/**
 * @summary Update a stop
 */
export const UpdateStopParams = zod.object({
  "stopId": zod.coerce.number().int()
})

export const UpdateStopBody = zod.object({
  "arrivalDate": zod.coerce.date().optional(),
  "departureDate": zod.coerce.date().optional(),
  "notes": zod.string().optional()
})

export const UpdateStopResponse = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "city": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "stopOrder": zod.int(),
  "notes": zod.string()
})


/**
 * @summary Delete a stop
 */
export const DeleteStopParams = zod.object({
  "stopId": zod.coerce.number().int()
})

export const DeleteStopResponse = zod.void()


/**
 * @summary List trip activities
 */
export const ListTripActivitiesParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const ListTripActivitiesResponseItem = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "stopId": zod.int(),
  "activity": zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
}),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "durationMinutes": zod.int(),
  "cost": zod.number(),
  "notes": zod.string()
})
export const ListTripActivitiesResponse = zod.array(ListTripActivitiesResponseItem)


/**
 * @summary Add an activity to a trip
 */
export const AddTripActivityParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const addTripActivityBodyCostMin = 0;



export const AddTripActivityBody = zod.object({
  "stopId": zod.int(),
  "activityId": zod.int(),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "cost": zod.number().min(addTripActivityBodyCostMin).optional(),
  "notes": zod.string().optional()
})

export const AddTripActivityResponse = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "stopId": zod.int(),
  "activity": zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
}),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "durationMinutes": zod.int(),
  "cost": zod.number(),
  "notes": zod.string()
})


/**
 * @summary Update a trip activity
 */
export const UpdateTripActivityParams = zod.object({
  "activityId": zod.coerce.number().int()
})

export const updateTripActivityBodyCostMin = 0;



export const UpdateTripActivityBody = zod.object({
  "activityDate": zod.coerce.date().optional(),
  "startTime": zod.string().optional(),
  "cost": zod.number().min(updateTripActivityBodyCostMin).optional(),
  "notes": zod.string().optional()
})

export const UpdateTripActivityResponse = zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "stopId": zod.int(),
  "activity": zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
}),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "durationMinutes": zod.int(),
  "cost": zod.number(),
  "notes": zod.string()
})


/**
 * @summary Remove an activity
 */
export const DeleteTripActivityParams = zod.object({
  "activityId": zod.coerce.number().int()
})

export const DeleteTripActivityResponse = zod.void()


/**
 * @summary Calculate trip budget
 */
export const GetTripBudgetParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const GetTripBudgetResponse = zod.object({
  "total": zod.number(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "averagePerDay": zod.number(),
  "durationDays": zod.int(),
  "categories": zod.array(zod.object({
  "name": zod.string(),
  "value": zod.number(),
  "color": zod.string()
}))
})


/**
 * @summary Search cities
 */
export const ListCitiesQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "region": zod.coerce.string().optional()
})

export const ListCitiesResponseItem = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
})
export const ListCitiesResponse = zod.array(ListCitiesResponseItem)


/**
 * @summary Search activities
 */
export const ListActivitiesQueryParams = zod.object({
  "search": zod.coerce.string().optional(),
  "category": zod.coerce.string().optional()
})

export const ListActivitiesResponseItem = zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
})
export const ListActivitiesResponse = zod.array(ListActivitiesResponseItem)


/**
 * @summary Create a public share link
 */
export const ShareTripParams = zod.object({
  "tripId": zod.coerce.number().int()
})

export const ShareTripResponse = zod.object({
  "token": zod.string(),
  "url": zod.string()
})


/**
 * @summary View a shared trip
 */
export const GetSharedTripParams = zod.object({
  "token": zod.coerce.string()
})

export const GetSharedTripResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "description": zod.string(),
  "startDate": zod.coerce.date(),
  "endDate": zod.coerce.date(),
  "budget": zod.number(),
  "currency": zod.string(),
  "status": zod.string(),
  "cities": zod.int(),
  "activities": zod.int(),
  "coverImage": zod.string(),
  "isPublic": zod.boolean()
}).and(zod.object({
  "stops": zod.array(zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "city": zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "country": zod.string(),
  "region": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "costIndex": zod.string(),
  "popularity": zod.number()
}),
  "arrivalDate": zod.coerce.date(),
  "departureDate": zod.coerce.date(),
  "stopOrder": zod.int(),
  "notes": zod.string()
})),
  "tripActivities": zod.array(zod.object({
  "id": zod.int(),
  "tripId": zod.int(),
  "stopId": zod.int(),
  "activity": zod.object({
  "id": zod.int(),
  "cityId": zod.int(),
  "name": zod.string(),
  "cityName": zod.string(),
  "category": zod.string(),
  "description": zod.string(),
  "image": zod.string(),
  "durationMinutes": zod.int(),
  "estimatedCost": zod.number(),
  "rating": zod.number()
}),
  "activityDate": zod.coerce.date(),
  "startTime": zod.string(),
  "durationMinutes": zod.int(),
  "cost": zod.number(),
  "notes": zod.string()
}))
}))


/**
 * @summary Get current profile
 */
export const GetProfileResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "email": zod.string(),
  "country": zod.string(),
  "initials": zod.string().optional()
})


/**
 * @summary Update current profile
 */



export const UpdateProfileBody = zod.object({
  "name": zod.string().min(1).optional(),
  "country": zod.string().optional()
})

export const UpdateProfileResponse = zod.object({
  "id": zod.int(),
  "name": zod.string(),
  "email": zod.string(),
  "country": zod.string(),
  "initials": zod.string().optional()
})


