/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
export interface BudgetCategory {
    name: string;
    value: number;
    color: string;
}
//# sourceMappingURL=budgetCategory.d.ts.map