/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import type { BudgetCategory } from './budgetCategory';

export interface BudgetSummary {
  total: number;
  budget: number;
  currency: string;
  status: string;
  averagePerDay: number;
  durationDays: number;
  categories: BudgetCategory[];
}
