/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
export interface City {
    id: number;
    name: string;
    country: string;
    region: string;
    description: string;
    image: string;
    costIndex: string;
    popularity: number;
}
//# sourceMappingURL=city.d.ts.map