/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import type { City } from './city';
import type { DashboardStats } from './dashboardStats';
import type { Profile } from './profile';
import type { Trip } from './trip';
export interface Dashboard {
    profile: Profile;
    stats: DashboardStats;
    upcomingTrips: Trip[];
    destinations: City[];
}
//# sourceMappingURL=dashboard.d.ts.map