/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import type { StatusParameter } from './statusParameter';
export type ListTripsParams = {
    status?: StatusParameter;
};
//# sourceMappingURL=listTripsParams.d.ts.map