/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */

export interface Trip {
  id: number;
  name: string;
  description: string;
  startDate: Date;
  endDate: Date;
  budget: number;
  currency: string;
  status: string;
  cities: number;
  activities: number;
  coverImage: string;
  isPublic: boolean;
}
