/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */

export interface TripInput {
  /** @minLength 1 */
  name: string;
  description?: string;
  startDate: Date;
  endDate: Date;
  /** @minimum 0 */
  budget?: number;
  currency?: string;
  coverImage?: string;
}
