/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import type { Stop } from './stop';
import type { Trip } from './trip';
import type { TripActivity } from './tripActivity';

export type TripDetail = Trip & {
  stops: Stop[];
  tripActivities: TripActivity[];
};
