/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * GlobeTrotter travel planning API
 * OpenAPI spec version: 0.1.0
 */
import type { Activity } from './activity';

export interface TripActivity {
  id: number;
  tripId: number;
  stopId: number;
  activity: Activity;
  activityDate: Date;
  startTime: string;
  durationMinutes: number;
  cost: number;
  notes: string;
}
